version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx-default-site.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./www:/var/www/html
